apiVersion: v2
name: kiwix-helm-chart
description: Helm chart for deploying kiwix-serve with automated ZIM file downloads
type: application
version: 0.4.1
appVersion: "0.4.1"
maintainers:
  - name: jacaudi
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
